replicaCount: 3

image:
  repository: 506456084401.dkr.ecr.eu-west-1.amazonaws.com/api
  # Image Updater keeps this in sync automatically after each CodeBuild run
  # Never use 'latest' — the SHA makes every deployment traceable to a specific commit
  tag: decf237ec12e5726c3cbc6a5e84fd17ade829aaa

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

hpa:
  enabled: false
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilization: 70
